"use client"

import React from 'react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import '../assets/styles/globals.css'
import { Golos_Text } from 'next/font/google'
import { Provider } from 'react-redux'
import {persistor, store} from '../store/store'
import AuthProvider from '../providers/auth-provider/auth.provider'
import { TypeComponentAuthFields } from '../providers/auth-provider/auth-pages.types'
import { PersistGate } from 'redux-persist/es/integration/react'

const inter = Golos_Text({ subsets: ['latin'] })
  
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app', 
}

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false
    }
  }
})

const RootLayout = ({
  children,
  Component
}: {
  children: React.ReactNode,
  Component: TypeComponentAuthFields
}) => {
  return (
          <html lang="en">
            <body className={inter.className}>
          <QueryClientProvider client={queryClient} >
            <Provider store={store}> 
              <PersistGate persistor={persistor} loading={null}>
                <AuthProvider Component={{ isOnlyUser: Component?.Component?.isOnlyUser}}>
                  {children} 
                </AuthProvider>
              </PersistGate>
            </Provider>
          </QueryClientProvider> 
            </body>
          </html>
  )
}

export default RootLayout